Include bootstrap.sh instructions
simsong/bulk_extractor pull request #352
Opened 2022-03-30 21:52 UTC by edsu

I think it would be useful to mention in the README.md that you need to run `bootstrap.sh` to generate the configure command. I don't believe it's mentioned in the INSTALL, but people will probably see the README on GitHub first anyway.

2022-03-30 23:23 UTC, simsong commented
You don’t need to do this if you run from the .tar.gz distribution. This is only necessary if run from a git clone.  Can you make this clear?

2022-03-31 00:41 UTC, simsong requested changes
If you are going to do this, then you are going to need to explain the difference between running the `.tar.gz` installer, which includes the configure command, and running `bootstrap`, which runs the whole autoconf tool chain to make it. And since the bootstrap behaves differently on different platforms, you're going to need to explain that as well. 

Can you look to see how other open source projects handle this? Very few put the configure script into the git repo.

2022-03-31 01:17 UTC, edsu commented
I assumed this would be the response. Good luck!

2022-03-31 01:19 UTC, simsong commented
> I assumed this would be the response. Good luck!

Why did you close the request? It's reasonable. People who are used to open source development with autoconf understand the situation, but others don't. I just don't want to tell everybody to run the program. So I would like to make the instructions more clear. Do you think that's a bad idea?

2022-03-31 01:28 UTC, simsong commented
Do you have no intention because you think that it's a bad request, and you disagree that it is needed?

2022-03-31 02:20 UTC, edsu commented
I don't think it's a bad request. It's just beyond my abilities to act on without spending more time on it, which I don't really have unfortunately. I thought a small incremental change would be helpful.

I did start with `bulk_extractor-2.0.0.tar.gz` which also did not seem to include a `configure`.  If instructions for working with the Git repo are added it would be good to indicate that a `git clone --recurse-submodules` is needed. Otherwise bootstrap.sh will fail. Perhaps it is by design but the `bulk_extractor-2.0.0.tar.gz` seems to lack dfxml_schema and src/be20_api. This also causes bootstrap.sh to fail.

2022-03-31 02:30 UTC, simsong commented
Huh. That's odd. From where did you download bulk_extractor-2.0.0.tar.gz? The files available at https://github.com/simsong/bulk_extractor/releases/tag/v2.0.0 are GitHub "releases" which are just not useful for projects that include submodules, for the reasons that you note. But I could add the file `bulk_extractor-2.0.0.tar.gz` there if you think it would be useful.

I also think that it's getting time to delete all of the old releases. What do you think?

2022-03-31 03:11 UTC, edsu commented
I downloaded the release from GitHub, which is how projects tend to use GitHub in my experience. Having the old release versions is useful. For example today I used it because I was comparing output between two versions. I'm just a dabbler in bulk_extractor land, so I don't think my opinions count for much.

2022-03-31 11:39 UTC, simsong commented
You think that it's useful having these old releases at digitalcorpora?
https://downloads.digitalcorpora.org/downloads/bulk_extractor/
![image](https://user-images.githubusercontent.com/1594284/161046758-22ef29eb-ef21-4b6a-81f9-5d49d51ed798.png)

2022-06-18 23:01 UTC, simsong approved these changes

2022-06-18 23:01 UTC, merged